modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/SilentChaos512/TorchBandolier/issues"
displayURL="https://minecraft.curseforge.com/projects/torch-bandolier"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="SilentChaos512"

[[mods]]
    modId="torchbandolier"
    version="${file.jarVersion}"
    displayName="Torch Bandolier"
    #updateJSONURL="http://myurl.me/"
    description='''
    Adds an item which stores many torches.
    '''

[[dependencies.torchbandolier]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.torchbandolier]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.torchbandolier]]
    modId="silentlib"
    mandatory=true
    versionRange="[4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.torchbandolier]]
    modId="silentgear"
    mandatory=false
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"
